### ISSUE TITLE
consider serving src (or higher thumb) images in gallery on mobile

### ISSUE THREAD

**Issue by pdt1806** [tobycm/emochoice#4]
reasons:
- current thumb images look awful on mobile (mobile is closer to users' eyes, and only one image serves at the time, meaning the image is very large, detailed to users, and serving low res images is not a good idea)
- zoom overlay is not applicable on mobile (unfamiliar behavior from mobile users), instead they would just zoom in with 2 fingers, that's why high res images need to be served directly

more reasons to come but basically, just pull out your phone to see that images are not good on mobile
and ultimately, egg wont implement zoom overlay on mobile devices (reason no.2).

**Comment by tobycm** [comment]
Hmm good idea.
I think the list of images under the product image should still be thumbnails though.
Kinda unrealistic thinking someone would zoom into a list of images that are meant to press

What's your opinion?

**Comment by pdt1806** [comment]
> Hmm good idea. I think the list of images under the product image should still be thumbnails though. Kinda unrealistic thinking someone would zoom into a list of images that are meant to press

well i was talking about the Gallery page so that's not the point here.

so yeah the images in Gallery page on mobile should be as a higher res

**Comment by tobycm** [comment]
Fixed in https://github.com/tobycm/emochoice/commit/2bb2b62eca7cd78158b8e6f8a325dfd773a682e0
